"use client";
import { ApolloProvider } from "@apollo/client";
import "./globals.css";
import { Inter } from "next/font/google";
import { client } from "@/libs/Apollo";
import DashboardPage from "@/component/Dashboard/DashboardLayout";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
